version: '3'

services:
  mongo:
    container_name: openhim-mongo
    ports:
      - "27017:27017"
    image: mongo:3.4
    
  core:
    container_name: openhim-core
    image: jembi/openhim-core
    environment:
      - mongo_url=mongodb://mongo/openhim
      - mongo_atnaUrl=mongodb://mongo/openhim
    ports:
      - "8080:8080"
      - "5000:5000"
      - "5001:5001"
      - "5050:5050"
      - "5051:5051"
      - "5052:5052"
      - "7788:7788"
    depends_on:
      - mongo
  
  console:
    container_name: openhim-console
    image: jembi/openhim-console
    ports:
        - "9000:80"
    volumes:
      - ./default.json:/usr/share/nginx/html/config/default.json

  labToOmrsMediator:
    container_name: savics-labToOmrs
    image: savicsorg/labToOmrs:latest
    ports:
      - "4000:4000"
    depends_on:
      - core
    volumes:
      - ./labToOmrs_config/:/usr/src/app/savics/labToOmrsMediator/config/
    restart: always



  omrsToNidaMediator:
    container_name: savics-omrsToNida
    image: savicsorg/omrsToNida:latest
    ports:
      - "4001:4001"
    depends_on:
      - core
    volumes:
      - ./omrsToNida_config/:/usr/src/app/savics/omrsToNidaMediator/config/
    restart: always


